name: release

on:
  workflow_dispatch:
  push:
    branches: [master]

env:
    luajit_ver: 2.1.0-beta3
    sdl_ver: 2.24.0

jobs:
  build:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Cache libs
        id: cache-libs
        uses: actions/cache@main
        with:
          path: |
            external
          key: ${{ runner.os }}-${{ env.luajit_ver }}-${{ env.sdl_ver }}-1

      - name: Install Packages
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y gcc-mingw-w64-i686 mingw-w64-i686-dev binutils-mingw-w64-i686 gcc-multilib wget libsdl2-dev libasound2-dev libsamplerate-dev
          sudo apt-get install -y build-essential

      - name: build
        run: |
          ./contrib/build-release.sh

      - name: Create Artifact
        run: |
          mkdir -p artifact/dein
          cp -r release/* artifact/dein

      - name: Publish Artifact
        uses: actions/upload-artifact@v3
        with:
          name: dein
          path: artifact
          retention-days: 1
  upload:
    name: Create release and upload artifacts
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@main
      - name: Create zip
        run: |
          ls -alFR
          cd dein
          zip -r ../dein.zip dein/
      - name: Create release and upload artifacts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          wget -q https://github.com/TheAssassin/pyuploadtool/releases/download/continuous/pyuploadtool-x86_64.AppImage
          chmod +x pyuploadtool-x86_64.AppImage
          ./pyuploadtool-x86_64.AppImage dein.zip
