name: Emscripten version
on:
  push:
    branches: [master]
  workflow_dispatch:

env:
    emsdk_ver: 3.1.28

jobs:
  build:
    name: Emscripten version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Cache emsdk
        id: cache-emsdk
        uses: actions/cache@main
        with:
          path: emsdk
          key: ${{ runner.os }}-${{ env.emsdk_ver }}

      - name: Install Packages
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y git

      - if: ${{ steps.cache-emsdk.outputs.cache-hit != 'true' }}
        name: Prep
        run: |
          git clone https://github.com/emscripten-core/emsdk.git
          cd emsdk
          ./emsdk install ${{ env.emsdk_ver }}
          ./emsdk activate ${{ env.emsdk_ver }}

      - name: Build
        run: |
          cd emsdk
          export WORKSPACE="${{github.workspace}}/emsdk/env"
          . emsdk/emsdk_env.sh
          ./contrib/make-emscripten.sh

      - name: Create Artifact
        run: |
          mkdir -p ./release/rein-em
          cp rein.data rein.wasm rein.js ./release/rein-em
          cp contrib/rein.html ./release/rein-em

      - name: Publish Artifact
        uses: actions/upload-artifact@main
        with:
          name: rein-em
          path: release
          retention-days: 1
